### PR TITLE
Adding option 'dataOnly' to return an Array of Objects with values instead of Html formatted Strings

### PR DESCRIPTION
**Pull request by OxyDesign**
I needed it for a project but with data in objects (instead of plain html) therefore I've made this change so I PR it in case you find it useful but that might be not of interest.
Thanks

### CODE REVIEW

**Comment by jasonmayes** [comment]
Thanks, I shall take a look when I have a moment - just got back from holiday so still catching up on a lot of things!

**Comment by OxyDesign** [comment]
Of course, take your time, there's no rush. And if you think it could be of interest but in a slightly different way please let me know and I will amend it. Thanks

**Comment by OxyDesign** [comment]
Hey, did you find some time to check it ? Thanks

**Comment by jasonmayes** [comment]
Sorry for delay here. I have added some minor comments. If you could just address those and also add documentation to the exampleUsage.js (eg after line 61) along with a config for example usuage that would be great. I can then look at merging.

**Comment by OxyDesign** [comment]
It's done
The example is based on Angular usage, because it was my use case. Hope it's fine
Feel free to tell me if everything is fine
Thanks

**Comment by OxyDesign** [comment]
Done
Thanks

**Comment by jasonmayes** [comment]
Thanks for this OxyDesign!

**Comment by OxyDesign** [comment]
You're welcome

**Pull request merged**
