### PR TITLE
Custom callback gets more raw data

### PR DESCRIPTION
**Pull request by bfred-it**
This only gives more already-available data to the customCallback, allowing custom layouts without having to reparse `arrayTweets`, for example, if I only want the text of the first tweet:

	function customCallback (html, elements) {
		document.getElementById('tweet').appendChild( elements.tweets[0] );
	}

Documentation will follow if you're interested in pulling this in.

### CODE REVIEW

**Comment by bfred-it** [comment]
Let me know if I should solve the conflicts

**Comment by jasonmayes** [comment]
Thanks for the contirbutions! One thing - I do not see index.html updated anywhere?

**Comment by bfred-it** [comment]
You mean I should bump it to *update 14?* Should we switch to [semver](http://semver.org/)?

**Comment by jasonmayes** [comment]
I mean there is no dom element with id example7 / 8 / 9 for it to render into etc.

**Comment by hovancik** [comment]
i would love to see this merged ;]

**Comment by bfred-it** [comment]
There's no example 8/9, they require browserify and AMD. I added this new raw feature between example 5 and 6

**Comment by bfred-it** [comment]
Ping

**Comment by jasonmayes** [comment]
My turn to be sorry for delay. This is now a duplicate of https://github.com/jasonmayes/Twitter-Post-Fetcher/pull/50 I believe (which is mergable)

**Pull request closed without merging**
