### PR TITLE
Added permalink and caching ability

### PR DESCRIPTION
**Pull request by jonnyhaynes**
Wrapped the outputted time with the permalink as is standard with Twitter. Can be configurable like everything else with `showPermalinks` option in config.

### CODE REVIEW

**Comment by dvorapa** [comment]
:+1:

**Comment by jonnyhaynes** [comment]
Updated the code to include the caching of tweets. This is again configurable by the `cacheTweets` option in the config, and is set to false by default.

**Comment by jasonmayes** [comment]
Thanks Jonny for the PR.

I need to think about this carefully as you are setting cookies. In the EU we have a Cookie law such that if you are using Cookies, the site must display an agreement to comply with that. It may be best for this to live as a fork for now until I figure out how it may impact sites that update to this. I want to keep this component as simple and hassle free as possible for the master version.

The permalinks code part looks good though - if you could create a seperate PR just for those changes, we can look in to merging that part of your work. :-)

Jason

**Comment by jonnyhaynes** [comment]
@jasonmayes I know about the cookie law, I'm from the UK. Surely by setting it to false by default (as it currently is) will suffice as it's not something that would work out of the box? Just a thought. 

I'll sort out the separate pull request.

Cheers,
Jonny

**Pull request closed without merging**
