### PR TITLE
Added 13.0.0 version tag

### PR DESCRIPTION
**Pull request by growdigital**
Just to make less error messages when using Bower :)

### CODE REVIEW

**Comment by growdigital** [comment]
I _think_ it's the way to add a tag, I had to add an empty space to the README to get changes to be recognised.

**Comment by jasonmayes** [comment]
Would one not change https://github.com/jasonmayes/Twitter-Post-Fetcher/blob/master/bower.json version number?

**Comment by growdigital** [comment]
@jasonmayes if your `bower.json` dependency is written like this:
```
		"dependencies": {
				"twitter-fetcher": "13.0.0"
		}
```
then you get this error message when you `$ bower install`:
```
bower twitter-fetcher#13.0.0     ENORESTARGET No tag found that was able to satisfy 13.0.0
Additional error details:
No versions found in git://github.com/jasonmayes/Twitter-Post-Fetcher.git
```

If you then omit the version number from the dependency in `bower.json`, then it installs.

So, it does work as is *but* it means you can't tie down the version in bower, which _could_ cause problems for people wanting a specific version.

**Comment by jasonmayes** [comment]
I am not sure I am quite following. Apologies (I did have a busy day today!) So you are saying I should remove the version number from bower.json completely?

**Comment by davegudge** [comment]
When previously adding a component to [rails-assets.org](https://rails-assets.org/components/new), I have found that tagging the version in the repository allows the version to be resolved: e.g:

`git tag 13.0.0` followed by `git push --tags`

screen shot 2015-04-26 at 16 07 28

**Comment by jasonmayes** [comment]
Thanks for contributing :-)

**Comment by davegudge** [comment]
fyi: merging this PR won't tag the repository, you'll need to run the cmd's in my comment above: 

`git tag 13.0.0` followed by `git push --tags`

once tagged and pushed, you should see the tag [here](https://github.com/jasonmayes/Twitter-Post-Fetcher/tags).

That will allow anything reading the [version](https://github.com/jasonmayes/Twitter-Post-Fetcher/blob/master/bower.json#L4) in the bower.json file to be resolved to the version of the code in the repository at a given point in time, i.e. the commit that is tagged with `13.0.0`

Hope that makes sense and helps.

**Comment by jasonmayes** [comment]
Done :)

**Comment by davegudge** [comment]
:+1:

**Pull request merged**
