### PR TITLE
Set avatar IMG 'src' to data-src-2x content

### PR DESCRIPTION
**Pull request by JemBijoux**
Images returned by twitterImg syndication api no longer include
src attributes, so add a function to swap the 2x-src into the src
attribute.

### CODE REVIEW

**Comment by ceremy1** [comment]
thanks so much  @JemBijoux

**Comment by bhanurao** [comment]
The new twitterFetcher_mins.js gives an error on IE10 
Message : Unable to get property 'src-2x' of undefined or null reference

**Comment by JemBijoux** [comment]
Hmm, that's not good. @bhanurao were you able to confirm if it worked fine with the normal version? Perhaps the minification tool I used munged something up. I can always resubmit this PR with only the full size version instead if the project maintainer wants to perform minification themselves.

**Comment by bhanurao** [comment]
The same issue the the non-minified version too, I think the use of dataset is not supported <IE11 , error is on this line
avatarImg.src = avatarImg.dataset['src-2x'];

**Comment by JemBijoux** [comment]
Thanks for pointing that out @bhanurao, really good call on the use of dataset there. I made another push and changed to reading the attribute with `.getAttribute()` instead. (I minified it once more too.)

If you're able, would you mind giving it one more shot and let me know if that sorts it? Thanks again for pointing that out and trying against both versions.

**Comment by jasonmayes** [comment]
Thanks guys! Merged.

**Pull request merged**
