### PR TITLE
Fix for #165

### LINKED ISSUE #165: Uncaught TypeError: Cannot read property 'getAttribute' of undefined
Twitter Post Fetcher v17.0.3 appears to be crashing, including on the [Codepen demos](http://codepen.io/jasonmayes/pen/Ioype). Currently the stack trace points to this method:

```Uncaught TypeError: Cannot read property 'getAttribute' of undefined at swapDataSrc```

```
function swapDataSrc(element) {
    var avatarImg = element.getElementsByTagName('img')[0];
    avatarImg.src = avatarImg.getAttribute('data-src-2x');
    return element;
}
```

From `callback`:

```
if (printUser) {
     authors.push(swapDataSrc(tmp[x].getElementsByClassName('timeline-Tweet-author')[0]));
}
```

### PR DESCRIPTION
**Pull request by Tombarr**
Null check on elements with `data-scribe` attribute, resolves #165 (not #160 😬)

### CODE REVIEW

**Comment by ADmad** [comment]
While this patch fixes the particular error and script continues to work profile icon for the tweet author is no longer available.

**Comment by mafia99** [comment]
I am sure someone will write a better fix for profile icons. but what I have done is following.
`var authorName = authors[n].getElementsByClassName('TweetAuthor-screenName')[0].innerHTML;
							var authorImg = '';
							if(authorName){
								authorImg = '';
								
							}` 
and then use authorImage where I needed. In my case it was inside element with class name 'user'

**Comment by extra-su** [comment]
I've implemented these changes but still it doesn't fix the issue, I'm no longer getting error message but still tweets doesn't get displayed.

**Comment by mufaddalmw** [comment]
@Tombarr @ADmad I've implemented these changes but still it doesn't fix the issue, I'm no longer getting error message but still tweets doesn't get displayed.

**Comment by jasonmayes** [comment]
This does indeed seem to break profile image :-/ But is the same code essentially just with the extra check which suggests profile image has changed.

**Comment by jasonmayes** [comment]
Update: It seems the twitter widget code no longer contains the profile image, which is why this bug happened in the first place. Once the code comments have been addressed I will merge this fix so it works, but it seems profile images are no longer available unless someone figures out a way to link username to profile photo but it seems like a hash is used for the jpg name so that may be hard.

**Comment by jasonmayes** [comment]
Update: I think I figured out how to get image. Im gonna take changes here and make a fix. Will update in a bit

**Comment by jasonmayes** [comment]
I have written a a patch to deal with the image issue too. Please update to v18.0.0

**Pull request closed without merging**
